### PR TITLE
Line2d and GreyscaleConnectedComponentLabeler bug fixes

### PR DESCRIPTION
**Pull request by HaleB**
Added distanceToLine method on line2d that calculates the shortest distance from the point to the line and use that function to fix a bug on isOnLine where distance was calculated incorrectly for lines that are nearly vertical.

Fixed flood fill bug on GreyscaleConnectedComponentLabeler: Images with horizontal lines of the target color would add the same pixel multiple times. Getting exponentially slower the longer the horizontal lines were.

Note that the floodFill method is in a few other places in the code and may need fixing there as well.

### CODE REVIEW

**Comment by jonhare** [comment]
Can you check the latest version of GreyscaleConnectedComponentLabeler? I think I've fixed the issue whilst still keeping the stack-based scanline filling approach, rather than resorting to the naive stack-based approach (see the third algorithm here: http://en.wikipedia.org/wiki/Flood_fill). The bug crept in because in out implementation the input and output are different images, so we need extra checks.

**Comment by HaleB** [comment]
I have not had time to check it yet. The issue was obvious for a 1600x1200 image of one color containing a 200x200 rectangle of another color as it took many seconds to process (felt like minutes). I am swamped getting things done before going on vacation tomorrow. I might have some time week after next.

**Comment by HaleB** [comment]
Gave it a quick check and it appears to still be fast, so lets call it fixed.

**Comment by HaleB** [comment]
Full test: Your version works great. Bravo

On my test image 1280x960 Here is how it stacks up
pixels tested          Time          Version
697,322,712          4 min         original  
    2,431,100          4 sec         mine
    1,216,030          3 sec         yours

**Comment by jonhare** [comment]
Bug in labeller is fixed independentyl of the pull request. Commit 5d65528613bcf59ef8a00f745c51402b612267d0 incorporates the changes to `Line2d`.

**Pull request closed without merging**
